trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - bash: |
      curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      databricks -v
    displayName: Install Databricks CLI

  - bash: |
      databricks bundle validate -t dev
    displayName: Validate Databricks bundle
    env:
      DATABRICKS_HOST: $(DATABRICKS_HOST)
      DATABRICKS_CLIENT_ID: $(DATABRICKS_CLIENT_ID)
      DATABRICKS_CLIENT_SECRET: $(DATABRICKS_CLIENT_SECRET)

  - bash: |
      databricks bundle deploy -t dev
    displayName: Deploy Databricks bundle
    env:
      DATABRICKS_HOST: $(DATABRICKS_HOST)
      DATABRICKS_CLIENT_ID: $(DATABRICKS_CLIENT_ID)
      DATABRICKS_CLIENT_SECRET: $(DATABRICKS_CLIENT_SECRET)
